.PHONY: generate build test clean deps fmt lint \
        web-build web-dev keygen send setup-env

# Generate ogen code from OpenAPI schema
generate:
	go tool ogen --config api/ogen.yaml --target api --package api --clean api/openapi.yaml

# Build all binaries
build:
	go build -o bin/client ./cmd/client
	go build -o bin/keygen ./cmd/keygen

# Run tests
test:
	go test -v ./...

# Clean build artifacts
clean:
	rm -rf bin/
	rm -rf web/.next/

# Install dependencies
deps:
	go mod tidy
	cd web && npm install

# Format code
fmt:
	go fmt ./...

# Lint code
lint:
	go vet ./...

# === Next.js webhook server ===

# Build Next.js app
web-build:
	cd web && npm run build

# Run Next.js dev server
web-dev:
	cd web && npm run dev

# === Webhook commands (requires env.local from setup-env) ===

# Generate a new webhook secret
keygen:
	@go run ./cmd/keygen/

# Send webhook to Next.js server
send:
	go run ./cmd/client/

# Generate env.local files with consistent secrets
setup-env:
	@echo "Generating webhook secret..."
	@SECRET=$$(go run ./cmd/keygen/) && \
	echo "# Client environment - generated by 'make setup-env'" > env.local && \
	echo "WEBHOOK_TARGET_URL=http://localhost:3000/api/webhook" >> env.local && \
	echo "WEBHOOK_SECRET=$$SECRET" >> env.local && \
	echo "# Next.js server environment - generated by 'make setup-env'" > web/env.local && \
	echo "WEBHOOK_SECRET=$$SECRET" >> web/env.local && \
	echo "Generated:" && \
	echo "  - env.local (client)" && \
	echo "  - web/env.local (Next.js server)"
