// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ WebhookHandler = UnimplementedHandler{}

// UserEvent implements userEvent operation.
//
// Webhook sent when a user event occurs (created, updated, deleted).
func (UnimplementedHandler) UserEvent(ctx context.Context, req *WebhookEvent) (r UserEventRes, _ error) {
	return r, ht.ErrNotImplemented
}
