// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

type UserEventBadRequest ErrorResponse

func (*UserEventBadRequest) userEventRes() {}

type UserEventUnauthorized ErrorResponse

func (*UserEventUnauthorized) userEventRes() {}

// Ref: #/components/schemas/WebhookEvent
type WebhookEvent struct {
	// The type of the webhook event.
	Type string `json:"type"`
	// The event payload data.
	Data WebhookEventData `json:"data"`
}

// GetType returns the value of Type.
func (s *WebhookEvent) GetType() string {
	return s.Type
}

// GetData returns the value of Data.
func (s *WebhookEvent) GetData() WebhookEventData {
	return s.Data
}

// SetType sets the value of Type.
func (s *WebhookEvent) SetType(val string) {
	s.Type = val
}

// SetData sets the value of Data.
func (s *WebhookEvent) SetData(val WebhookEventData) {
	s.Data = val
}

// The event payload data.
type WebhookEventData map[string]jx.Raw

func (s *WebhookEventData) init() WebhookEventData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/WebhookResponse
type WebhookResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// GetSuccess returns the value of Success.
func (s *WebhookResponse) GetSuccess() bool {
	return s.Success
}

// GetMessage returns the value of Message.
func (s *WebhookResponse) GetMessage() string {
	return s.Message
}

// SetSuccess sets the value of Success.
func (s *WebhookResponse) SetSuccess(val bool) {
	s.Success = val
}

// SetMessage sets the value of Message.
func (s *WebhookResponse) SetMessage(val string) {
	s.Message = val
}

func (*WebhookResponse) userEventRes() {}
