// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ReceiveWebhook implements receiveWebhook operation.
//
// Endpoint to receive webhook events with standard-webhooks signature verification.
//
// POST /webhook
func (UnimplementedHandler) ReceiveWebhook(ctx context.Context, req *WebhookEvent) (r ReceiveWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}
